import = ["/home/albert/.config/alacritty/themes/one_dark.toml"]

[colors]
draw_bold_text_with_bright_colors = true

[font]
size = 16

[font.bold]
family = "JetBrainsMono NL Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd NL Font Mono"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono NL Nerd Font Mono"
style = "Italic"

[font.normal]
family = "JetBrainsMono NL Nerd Font Mono"
style = "Regular"

[scrolling]
history = 10000
multiplier = 3

[window]
opacity = 1

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 10
y = 10
